from pydantic import BaseModel, Field
from typing import List, Optional, Literal

# The structured output we want from the clinical document
class ProtocolExtraction(BaseModel):
    phase: str = Field(description="Clinical trial phase (e.g., Phase I, II, III, IV)")
    primary_endpoint: str = Field(description="The main objective measured to evaluate the drug")
    inclusion_criteria: List[str] = Field(description="List of criteria patients must meet")
    exclusion_criteria: List[str] = Field(description="List of criteria that disqualify patients")
    sample_size: int = Field(description="Target number of participants")

# Validation report generated by the reviewer agent
class ValidationReport(BaseModel):
    is_valid: bool = Field(description="True if the data passes clinical consistency checks")
    issues: List[str] = Field(default=[], description="List of contradictions or missing data points found")
    recommended_fixes: Optional[str] = Field(None, description="Guidance for the extraction agent on how to resolve issues")

# The central state shared across all nodes in LangGraph
class AgentWorkflowState(BaseModel):
    raw_document: str = ""
    extracted_data: Optional[ProtocolExtraction] = None
    validation_report: Optional[ValidationReport] = None
    loop_count: int = 0
    max_loops: int = 3
    current_errors: List[str] = []
